# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.

jobs:
    - name: nightly-desktop
      job:
          type: decision-task
          treeherder-symbol: Nd
          target-tasks-method: nightly_desktop
      run-on-projects:
          - comm-central
      when:
          by-project:
              # Match buildbot starts for now
              comm-central: [{hour: 10, minute: 0}]
              # No default

    - name: nightly-linux
      job:
          type: decision-task
          treeherder-symbol: Nd-Ln
          target-tasks-method: nightly_linux
      run-on-projects:
          - comm-central
      when: []  # never (hook only)

    - name: nightly-osx
      job:
          type: decision-task
          treeherder-symbol: Nd-OSX
          target-tasks-method: nightly_macosx
      run-on-projects:
          - comm-central
      when: []  # never (hook only)

    - name: nightly-win32
      job:
          type: decision-task
          treeherder-symbol: Nd-win32
          target-tasks-method: nightly_win32
      run-on-projects:
          - comm-central
      when: []  # never (hook only)

    - name: nightly-win64
      job:
          type: decision-task
          treeherder-symbol: Nd-win64
          target-tasks-method: nightly_win64
      run-on-projects:
          - comm-central
      when: []  # never (hook only)

    - name: periodic-update
      job:
          type: decision-task
          treeherder-symbol: Nfile
          target-tasks-method: file_update
      run-on-projects:
          - comm-central
      when:
          by-project:
              # No default branch
              comm-central:
                  - {weekday: 'Monday', hour: 10, minute: 0}
                  - {weekday: 'Thursday', hour: 10, minute: 0}
