# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: comm_taskgraph:reference_loader
base-path: taskcluster/ci

kind-dependencies:
    - packages

jobs:
    - debian7-amd64-build
    - debian7-base
    - debian7-i386-build
    - debian7-i386-packages
    - debian7-i386-raw
    - debian7-packages
    - debian7-raw
    - debian9-base
    - debian9-packages
    - debian9-raw
    - desktop1604-test
    - fetch
    - index-task
    - image_builder
    - lint
    - mingw32-build
    - periodic-updates
    - toolchain-build
    - update-verify
